<?php

namespace Database\Seeders;

use Fishinglog\Models\Badge;
use Illuminate\Database\Seeder;

class BadgeCatalogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $badges = [
            // 1. General Catch Volume Milestones
            [
                'slug' => 'vol_1',
                'name' => 'First Cast',
                'description' => 'First logged catch in the logbook',
                'category' => 'volume',
                'tier' => 'bronze',
                'points' => 10,
                'icon' => 'anchor',
                'image_path' => 'images/badges/badge_first_cast.webp',
                'rule_type' => 'volume_total',
                'rule_threshold' => 1,
                'accent_color' => 'amber',
                'sort_order' => 10,
            ],
            [
                'slug' => 'vol_5',
                'name' => 'High Five',
                'description' => 'Logged 5 career catches',
                'category' => 'volume',
                'tier' => 'bronze',
                'points' => 25,
                'icon' => 'hand',
                'image_path' => null,
                'rule_type' => 'volume_total',
                'rule_threshold' => 5,
                'accent_color' => 'amber',
                'sort_order' => 20,
            ],
            [
                'slug' => 'vol_10',
                'name' => 'Tenth Strike',
                'description' => 'Logged 10 career catches',
                'category' => 'volume',
                'tier' => 'bronze',
                'points' => 35,
                'icon' => 'zap',
                'image_path' => null,
                'rule_type' => 'volume_total',
                'rule_threshold' => 10,
                'accent_color' => 'amber',
                'sort_order' => 30,
            ],
            [
                'slug' => 'vol_25',
                'name' => 'Quarter Century',
                'description' => 'Logged 25 career catches',
                'category' => 'volume',
                'tier' => 'silver',
                'points' => 50,
                'icon' => 'shield',
                'image_path' => null,
                'rule_type' => 'volume_total',
                'rule_threshold' => 25,
                'accent_color' => 'slate',
                'sort_order' => 40,
            ],
            [
                'slug' => 'vol_50',
                'name' => 'Half Hundred',
                'description' => 'Logged 50 career catches',
                'category' => 'volume',
                'tier' => 'silver',
                'points' => 75,
                'icon' => 'award',
                'image_path' => null,
                'rule_type' => 'volume_total',
                'rule_threshold' => 50,
                'accent_color' => 'slate',
                'sort_order' => 50,
            ],
            [
                'slug' => 'vol_100',
                'name' => 'Century Club',
                'description' => 'Logged 100 career catches',
                'category' => 'volume',
                'tier' => 'gold',
                'points' => 100,
                'icon' => 'crown',
                'image_path' => 'images/badges/badge_century_club.webp',
                'rule_type' => 'volume_total',
                'rule_threshold' => 100,
                'accent_color' => 'amber',
                'sort_order' => 60,
            ],
            [
                'slug' => 'vol_150',
                'name' => 'Master Angler',
                'description' => 'Logged 150 career catches',
                'category' => 'volume',
                'tier' => 'platinum',
                'points' => 200,
                'icon' => 'sparkles',
                'image_path' => null,
                'rule_type' => 'volume_total',
                'rule_threshold' => 150,
                'accent_color' => 'cyan',
                'sort_order' => 70,
            ],

            // 2. Species Specialists
            [
                'slug' => 'spec_walleye_10',
                'name' => 'Walleye Stalker',
                'description' => '10 verified Walleye catches',
                'category' => 'species',
                'tier' => 'bronze',
                'points' => 30,
                'icon' => 'fish',
                'image_path' => 'images/badges/badge_walleye_stalker.webp',
                'rule_type' => 'species_count',
                'rule_threshold' => 10,
                'accent_color' => 'amber',
                'sort_order' => 110,
            ],
            [
                'slug' => 'spec_walleye_50',
                'name' => 'Walleye Maestro',
                'description' => '50 verified Walleye catches',
                'category' => 'species',
                'tier' => 'gold',
                'points' => 120,
                'icon' => 'fish',
                'image_path' => null,
                'rule_type' => 'species_count',
                'rule_threshold' => 50,
                'accent_color' => 'amber',
                'sort_order' => 120,
            ],
            [
                'slug' => 'spec_pike_10',
                'name' => 'Pike Hunter',
                'description' => '10 verified Northern Pike catches',
                'category' => 'species',
                'tier' => 'bronze',
                'points' => 30,
                'icon' => 'crosshair',
                'image_path' => 'images/badges/badge_pike_hunter.webp',
                'rule_type' => 'species_count',
                'rule_threshold' => 10,
                'accent_color' => 'emerald',
                'sort_order' => 130,
            ],
            [
                'slug' => 'spec_bass_10',
                'name' => 'Bronzeback Boss',
                'description' => '10 verified Smallmouth Bass catches',
                'category' => 'species',
                'tier' => 'bronze',
                'points' => 30,
                'icon' => 'trophy',
                'image_path' => 'images/badges/badge_bronzeback_boss.webp',
                'rule_type' => 'species_count',
                'rule_threshold' => 10,
                'accent_color' => 'emerald',
                'sort_order' => 140,
            ],
            [
                'slug' => 'spec_laker_5',
                'name' => 'Deep Cold Veteran',
                'description' => '5 verified Lake Trout catches',
                'category' => 'species',
                'tier' => 'silver',
                'points' => 50,
                'icon' => 'compass',
                'image_path' => null,
                'rule_type' => 'species_count',
                'rule_threshold' => 5,
                'accent_color' => 'cyan',
                'sort_order' => 150,
            ],

            // 3. Species Diversity
            [
                'slug' => 'div_sampler',
                'name' => 'Tackle Box Sampler',
                'description' => 'Catches logged across 3 distinct fish species',
                'category' => 'diversity',
                'tier' => 'bronze',
                'points' => 25,
                'icon' => 'layers',
                'image_path' => null,
                'rule_type' => 'diversity_distinct',
                'rule_threshold' => 3,
                'accent_color' => 'amber',
                'sort_order' => 210,
            ],
            [
                'slug' => 'div_biologist',
                'name' => 'Freshwater Biologist',
                'description' => 'Catches logged across 6 distinct fish species',
                'category' => 'diversity',
                'tier' => 'silver',
                'points' => 75,
                'icon' => 'book-open',
                'image_path' => 'images/badges/badge_biologist.webp',
                'rule_type' => 'diversity_distinct',
                'rule_threshold' => 6,
                'accent_color' => 'teal',
                'sort_order' => 220,
            ],
            [
                'slug' => 'div_grand_slam',
                'name' => 'Grand Slam',
                'description' => 'Catches logged across 9+ distinct fish species',
                'category' => 'diversity',
                'tier' => 'gold',
                'points' => 150,
                'icon' => 'gem',
                'image_path' => null,
                'rule_type' => 'diversity_distinct',
                'rule_threshold' => 9,
                'accent_color' => 'amber',
                'sort_order' => 230,
            ],

            // 4. Angler Cadence (Days on Water)
            [
                'slug' => 'cadence_5',
                'name' => 'Weekend Warrior',
                'description' => 'Catches logged across 5 distinct calendar days',
                'category' => 'cadence',
                'tier' => 'bronze',
                'points' => 25,
                'icon' => 'calendar',
                'image_path' => null,
                'rule_type' => 'cadence_distinct_days',
                'rule_threshold' => 5,
                'accent_color' => 'amber',
                'sort_order' => 310,
            ],
            [
                'slug' => 'cadence_15',
                'name' => 'River Rat',
                'description' => 'Catches logged across 15 distinct calendar days',
                'category' => 'cadence',
                'tier' => 'silver',
                'points' => 50,
                'icon' => 'sun',
                'image_path' => null,
                'rule_type' => 'cadence_distinct_days',
                'rule_threshold' => 15,
                'accent_color' => 'slate',
                'sort_order' => 320,
            ],
            [
                'slug' => 'cadence_30',
                'name' => 'Iron Logbook',
                'description' => 'Catches logged across 30 distinct calendar days',
                'category' => 'cadence',
                'tier' => 'gold',
                'points' => 100,
                'icon' => 'book',
                'image_path' => 'images/badges/badge_iron_logbook.webp',
                'rule_type' => 'cadence_distinct_days',
                'rule_threshold' => 30,
                'accent_color' => 'amber',
                'sort_order' => 330,
            ],

            // 5. Consecutive Seasons Streak
            [
                'slug' => 'streak_2_yr',
                'name' => 'Back-to-Back',
                'description' => 'Active across 2 consecutive calendar years',
                'category' => 'streak',
                'tier' => 'bronze',
                'points' => 25,
                'icon' => 'flame',
                'image_path' => null,
                'rule_type' => 'streak_years',
                'rule_threshold' => 2,
                'accent_color' => 'amber',
                'sort_order' => 410,
            ],
            [
                'slug' => 'streak_5_yr',
                'name' => 'Five-Season Veteran',
                'description' => 'Active across 5 consecutive calendar years',
                'category' => 'streak',
                'tier' => 'silver',
                'points' => 75,
                'icon' => 'star',
                'image_path' => null,
                'rule_type' => 'streak_years',
                'rule_threshold' => 5,
                'accent_color' => 'slate',
                'sort_order' => 420,
            ],
            [
                'slug' => 'streak_10_yr',
                'name' => 'Decade on the Water',
                'description' => 'Active across 10 consecutive calendar years',
                'category' => 'streak',
                'tier' => 'gold',
                'points' => 150,
                'icon' => 'award',
                'image_path' => null,
                'rule_type' => 'streak_years',
                'rule_threshold' => 10,
                'accent_color' => 'amber',
                'sort_order' => 430,
            ],

            // 6. Exploration & Big Waters
            [
                'slug' => 'exp_3_lakes',
                'name' => 'Lake Hopper',
                'description' => 'Verified catches across 3 distinct lakes',
                'category' => 'exploration',
                'tier' => 'bronze',
                'points' => 25,
                'icon' => 'map-pin',
                'image_path' => null,
                'rule_type' => 'lakes_distinct',
                'rule_threshold' => 3,
                'accent_color' => 'teal',
                'sort_order' => 510,
            ],
            [
                'slug' => 'exp_5_lakes',
                'name' => 'Voyageur',
                'description' => 'Verified catches across 5 distinct lakes',
                'category' => 'exploration',
                'tier' => 'silver',
                'points' => 50,
                'icon' => 'navigation',
                'image_path' => null,
                'rule_type' => 'lakes_distinct',
                'rule_threshold' => 5,
                'accent_color' => 'teal',
                'sort_order' => 520,
            ],
            [
                'slug' => 'exp_10_lakes',
                'name' => 'Pathfinder',
                'description' => 'Verified catches across 10 distinct lakes',
                'category' => 'exploration',
                'tier' => 'gold',
                'points' => 100,
                'icon' => 'map',
                'image_path' => null,
                'rule_type' => 'lakes_distinct',
                'rule_threshold' => 10,
                'accent_color' => 'teal',
                'sort_order' => 530,
            ],
            [
                'slug' => 'exp_high_seas',
                'name' => 'High Seas',
                'description' => 'Verified catch logged on Lake Superior or big open water',
                'category' => 'exploration',
                'tier' => 'gold',
                'points' => 100,
                'icon' => 'waves',
                'image_path' => 'images/badges/badge_high_seas.webp',
                'rule_type' => 'lake_superior_catch',
                'rule_threshold' => 1,
                'accent_color' => 'blue',
                'sort_order' => 540,
            ],
            [
                'slug' => 'exp_pioneer',
                'name' => 'New Water Pioneer',
                'description' => 'Present on expedition when a new lake was mapped',
                'category' => 'exploration',
                'tier' => 'gold',
                'points' => 100,
                'icon' => 'flag',
                'image_path' => 'images/badges/badge_new_water_pioneer.webp',
                'rule_type' => 'new_water_first',
                'rule_threshold' => 1,
                'accent_color' => 'amber',
                'sort_order' => 550,
            ],

            // 7. Weathered
            [
                'slug' => 'weather_barometer',
                'name' => 'Pressure Drop',
                'description' => 'Catch logged during rapid barometer pressure drop',
                'category' => 'weather',
                'tier' => 'silver',
                'points' => 50,
                'icon' => 'gauge',
                'image_path' => 'images/badges/badge_pressure_drop.webp',
                'rule_type' => 'weather_pressure_drop',
                'rule_threshold' => 1,
                'accent_color' => 'indigo',
                'sort_order' => 610,
            ],
            [
                'slug' => 'weather_storm',
                'name' => 'Weathered Iron',
                'description' => 'Catch logged in heavy rain, high winds, or storm',
                'category' => 'weather',
                'tier' => 'silver',
                'points' => 50,
                'icon' => 'cloud-lightning',
                'image_path' => 'images/badges/badge_weathered_iron.webp',
                'rule_type' => 'weather_storm_rain',
                'rule_threshold' => 1,
                'accent_color' => 'indigo',
                'sort_order' => 620,
            ],

            // 8. Nomad / Geographic Zones
            [
                'slug' => 'nomad_2_fmz',
                'name' => 'Cross-Border Angler',
                'description' => 'Catches across 2 distinct Fisheries Management Zones',
                'category' => 'nomad',
                'tier' => 'bronze',
                'points' => 30,
                'icon' => 'signpost',
                'image_path' => null,
                'rule_type' => 'fmz_distinct',
                'rule_threshold' => 2,
                'accent_color' => 'emerald',
                'sort_order' => 710,
            ],
            [
                'slug' => 'nomad_4_fmz',
                'name' => 'The Nomad',
                'description' => 'Catches across 4 distinct Fisheries Management Zones',
                'category' => 'nomad',
                'tier' => 'gold',
                'points' => 100,
                'icon' => 'globe',
                'image_path' => null,
                'rule_type' => 'fmz_distinct',
                'rule_threshold' => 4,
                'accent_color' => 'emerald',
                'sort_order' => 720,
            ],

            // 9. Total Fish Yardage
            [
                'slug' => 'yard_cabin',
                'name' => 'Around the Cabin',
                'description' => '100 cumulative feet (1,200") of fish caught',
                'category' => 'yardage',
                'tier' => 'bronze',
                'points' => 50,
                'icon' => 'home',
                'image_path' => 'images/badges/badge_around_cabin.webp',
                'rule_type' => 'cumulative_inches',
                'rule_threshold' => 1200,
                'accent_color' => 'amber',
                'sort_order' => 810,
            ],
            [
                'slug' => 'yard_touchdown',
                'name' => 'Touchdown',
                'description' => '100 cumulative yards (3,600") of fish caught',
                'category' => 'yardage',
                'tier' => 'silver',
                'points' => 100,
                'icon' => 'target',
                'image_path' => 'images/badges/badge_touchdown.webp',
                'rule_type' => 'cumulative_inches',
                'rule_threshold' => 3600,
                'accent_color' => 'slate',
                'sort_order' => 820,
            ],
            [
                'slug' => 'yard_mile',
                'name' => 'Going the Mile',
                'description' => '1 cumulative mile (63,360") of fish caught',
                'category' => 'yardage',
                'tier' => 'gold',
                'points' => 250,
                'icon' => 'milestone',
                'image_path' => null,
                'rule_type' => 'cumulative_inches',
                'rule_threshold' => 63360,
                'accent_color' => 'amber',
                'sort_order' => 830,
            ],

            // 10. Conservation (Catch & Release)
            [
                'slug' => 'rel_1',
                'name' => 'First Release',
                'description' => 'First verified released catch',
                'category' => 'conservation',
                'tier' => 'bronze',
                'points' => 10,
                'icon' => 'heart',
                'image_path' => 'images/badges/badge_first_release.webp',
                'rule_type' => 'released_catches',
                'rule_threshold' => 1,
                'accent_color' => 'emerald',
                'sort_order' => 910,
            ],
            [
                'slug' => 'rel_10',
                'name' => 'River Steward',
                'description' => '10 verified released catches',
                'category' => 'conservation',
                'tier' => 'bronze',
                'points' => 25,
                'icon' => 'leaf',
                'image_path' => null,
                'rule_type' => 'released_catches',
                'rule_threshold' => 10,
                'accent_color' => 'emerald',
                'sort_order' => 920,
            ],
            [
                'slug' => 'rel_25',
                'name' => 'Guardian of Waters',
                'description' => '25 verified released catches',
                'category' => 'conservation',
                'tier' => 'silver',
                'points' => 50,
                'icon' => 'shield-check',
                'image_path' => null,
                'rule_type' => 'released_catches',
                'rule_threshold' => 25,
                'accent_color' => 'emerald',
                'sort_order' => 930,
            ],
            [
                'slug' => 'rel_50',
                'name' => 'Honor Roll Release',
                'description' => '50 verified released catches',
                'category' => 'conservation',
                'tier' => 'silver',
                'points' => 75,
                'icon' => 'medal',
                'image_path' => null,
                'rule_type' => 'released_catches',
                'rule_threshold' => 50,
                'accent_color' => 'teal',
                'sort_order' => 940,
            ],
            [
                'slug' => 'rel_100',
                'name' => 'Century Conservation',
                'description' => '100 verified released catches',
                'category' => 'conservation',
                'tier' => 'gold',
                'points' => 150,
                'icon' => 'sun',
                'image_path' => null,
                'rule_type' => 'released_catches',
                'rule_threshold' => 100,
                'accent_color' => 'teal',
                'sort_order' => 950,
            ],

            // 11. Heritage & Crew Lore
            [
                'slug' => 'skunked',
                'name' => 'The Skunk',
                'description' => 'Zero catches on an expedition following 2 successful trips',
                'category' => 'heritage',
                'tier' => 'bronze',
                'points' => 10,
                'icon' => 'smile-plus',
                'image_path' => 'images/badges/badge_the_skunk.webp',
                'rule_type' => 'skunked_trip',
                'rule_threshold' => 1,
                'accent_color' => 'amber',
                'sort_order' => 1010,
            ],
            [
                'slug' => 'crew_maverick',
                'name' => 'Maverick',
                'description' => 'Top angler on expedition leaderboard',
                'category' => 'heritage',
                'tier' => 'gold',
                'points' => 100,
                'icon' => 'crown',
                'image_path' => 'images/badges/badge_maverick.webp',
                'rule_type' => 'crew_rank_first',
                'rule_threshold' => 1,
                'accent_color' => 'amber',
                'sort_order' => 1020,
            ],
            [
                'slug' => 'crew_goose',
                'name' => 'Goose',
                'description' => 'Second angler on expedition leaderboard',
                'category' => 'heritage',
                'tier' => 'silver',
                'points' => 50,
                'icon' => 'users',
                'image_path' => 'images/badges/badge_crew_goose.webp',
                'rule_type' => 'crew_rank_second',
                'rule_threshold' => 1,
                'accent_color' => 'slate',
                'sort_order' => 1030,
            ],
        ];

        foreach ($badges as $badgeData) {
            Badge::updateOrCreate(
                ['slug' => $badgeData['slug']],
                $badgeData
            );
        }
    }
}
