<?php

namespace Tests\Feature;

use Fishinglog\Models\Angler;
use Fishinglog\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\URL;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class AdminInviteAndQuickAddTest extends TestCase
{
    use RefreshDatabase;

    #[Test]
    public function public_register_route_is_disabled()
    {
        $response = $this->get('/register');
        $response->assertStatus(404);
    }

    #[Test]
    public function admin_can_generate_signed_invite_link_and_invited_user_can_register()
    {
        $admin = User::factory()->create(['type' => User::ADMIN_TYPE]);

        // 1. Admin generates invite
        $inviteResponse = $this->actingAs($admin)->post('/admin/users/invite', [
            'name' => 'Invited Angler',
            'email' => 'invited@example.com',
        ]);

        $inviteResponse->assertRedirect(route('admin.users'));
        $inviteResponse->assertSessionHas('status');
        $inviteResponse->assertSessionHas('invite_url');

        // 2. Generate valid relative signed URL
        $relativeSignedPath = URL::temporarySignedRoute(
            'register.invited',
            now()->addDays(7),
            ['email' => 'invited@example.com', 'name' => 'Invited Angler'],
            false
        );

        $getFormResponse = $this->get($relativeSignedPath);
        $getFormResponse->assertStatus(200);
        $getFormResponse->assertSee('Complete Account Setup');

        // 3. Complete invited registration
        $postResponse = $this->post($relativeSignedPath, [
            'name' => 'Invited Angler',
            'email' => 'invited@example.com',
            'password' => 'secret12345',
            'password_confirmation' => 'secret12345',
        ]);

        $postResponse->assertRedirect(route('home'));
        $this->assertDatabaseHas('users', ['email' => 'invited@example.com']);
        $this->assertDatabaseHas('anglers', ['firstName' => 'Invited Angler']);
    }

    #[Test]
    public function signed_invite_link_works_across_different_schemes_and_hostnames()
    {
        // 1. Generate relative signed path (as generated by laptop)
        $relativeSignedPath = URL::temporarySignedRoute(
            'register.invited',
            now()->addDays(7),
            ['email' => 'wife@example.com', 'name' => 'Jane Doe'],
            false
        );

        // 2. Access via production HTTPS NAS hostname
        $nasUrl = 'https://fishinglog.chzek-safe.synology.me' . $relativeSignedPath;
        $response = $this->get($nasUrl);
        $response->assertStatus(200);
        $response->assertSee('Complete Account Setup');
        $response->assertSee('wife@example.com');

        // 3. Complete registration via production URL
        $registerResponse = $this->post($nasUrl, [
            'name' => 'Jane Doe',
            'email' => 'wife@example.com',
            'password' => 'securepass123',
            'password_confirmation' => 'securepass123',
        ]);

        $registerResponse->assertRedirect(route('home'));
        $this->assertDatabaseHas('users', ['email' => 'wife@example.com', 'name' => 'Jane Doe']);
    }

    #[Test]
    public function tampered_or_invalid_signature_is_rejected_with_403()
    {
        $tamperedUrl = '/register/invited?email=hacker@example.com&name=Hacker&expires=9999999999&signature=invalid_hash';
        $response = $this->get($tamperedUrl);
        $response->assertStatus(403);
    }

    #[Test]
    public function admin_can_create_angler_account_via_canada_offline_quick_add()
    {
        $admin = User::factory()->create(['type' => User::ADMIN_TYPE]);

        $response = $this->actingAs($admin)->post('/admin/users/quick-add', [
            'name' => 'Canada Angler',
            'email' => 'canada@example.com',
            'password' => 'fieldpass123',
        ]);

        $response->assertRedirect(route('admin.users'));
        $response->assertSessionHas('status');

        $user = User::where('email', 'canada@example.com')->first();
        $this->assertNotNull($user);
        $this->assertEquals('pending_upstream', $user->sync_status);
        $this->assertNotEmpty($user->id);

        $angler = Angler::where('user_id', $user->id)->first();
        $this->assertNotNull($angler);
        $this->assertEquals('Canada', $angler->firstName);
        $this->assertEquals('pending_upstream', $angler->sync_status);
    }
}
